# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-19 07:09
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
        ),
    ]
